[package]
name = "bot"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git", rev = "master" }
flac = { git = "https://github.com/bonsaiden/flac.git", rev = "master" }
oauth2 = "*"
rand = "*"
dotenv = "*"
log = "*"
chrono = "*"
clippy = { version = "*", optional = true }
hound = "*"
clock_ticks = "*"
hyper = "0.8.1"
edit-distance = "^1.0.0"
toml = "0.1"

[features]
lint = ["clippy"]

